name = "PairingHamiltonian"
uuid = "0e39546d-869d-4f2a-bc21-e92ab20deea1"
authors = ["SotaYoshida <syoshida@cc.utsunomiya-u.ac.jp>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Combinatorics = "1.0.2"
Glob = "1.3.1"
Plots = "1.40.8"
